permissions:
  - '*'
sessions:
  session:
    useTLS: false
    redirect: true

jobs:
  preprocessing:
      ssh:
        remoteHost: ${{ inputs.cluster.resource.ip }}
      steps:
        - name: Checkout
          uses: parallelworks/checkout
          with:
            repo: https://github.com/parallelworks/interactive_session.git
            branch: v4-2026
            sparse_checkout:
              - ${{ inputs.service.name }}
        - name: Create Inputs
          run: |
            set -x
            # Write PW variables
            env | grep '^PW_' | grep -v 'PW_API_KEY' > inputs.sh
            # Write input form variables and ensure the pw agent is in the PATH
            cat <<'EOF' >> inputs.sh
            PATH=$HOME/pw:$PATH
            service_download_url="${{ inputs.service.download_url }}"
            service_password="${{ inputs.service.password }}"
            service_directory="${{ inputs.service.directory }}"
            juice_use_juice="${{ inputs.juice.use_juice }}"
            juice_pool_ids="${{ inputs.juice.pool_ids }}"
            juice_vram="${{ inputs.juice.vram }}"
            juice_cmd_args="${{ inputs.juice.cmd_args }}"
            JUICE_TOKEN="${{ org.JUICE_TOKEN }}"
            EOF
            if ! [ -z "${{ org.JUICE_TOKEN }}" ]; then
              echo "JUICE_TOKEN=${{ org.JUICE_TOKEN }}" >> inputs.sh
            fi
            # Remove empty variables
            sed -i '/=\s*$\|=undefined\s*$/d' inputs.sh
            # Add export= to all lines
            sed -i 's/^/export /' inputs.sh
        - name: Controller Preprocessing
          run: |
            set -x
            # This script prepares the target host and always runs in the controller node
            cp inputs.sh controller-preprocessing.sh
            cat ${{ inputs.service.name }}/controller-v3.sh >> controller-preprocessing.sh
            bash controller-preprocessing.sh
        - name: Create Service Script
          run: |
            # This script starts the service
            cp inputs.sh start-service.sh
            # TRANSITION CODE
            echo resource_jobdir=${PW_PARENT_JOB_DIR} >> start-service.sh
            # Write code common to all services
            cat <<'EOF' >> start-service.sh

            if [ -z "${service_port}" ]; then
              service_port=$(pw agent open-port)
            fi

            if [ -z "${service_port}" ]; then
              echo "$(date) ERROR: No service port found"
              exit 1            
            fi
            echo ${service_port} > SESSION_PORT
            hostname > HOSTNAME

            cleanup() {
                echo "$(date) Cleaning up..."
                kill -- -$$
            }

            trap cleanup EXIT INT TERM

            echo
            echo
            echo "$(date) STARTING SERVICE"
            echo
            touch job.started
            EOF
            cat ${{ inputs.service.name }}/start-template-v3.sh >> start-service.sh

  session_runner:
    needs:
      - preprocessing
    ssh:
        remoteHost: ${{ inputs.cluster.resource.ip }}
    steps:
      - uses: marketplace/script_submitter/v3.5
        with:
          resource: ${{ inputs.cluster.resource }}
          shebang: '#!/bin/bash'
          rundir: ${PW_PARENT_JOB_DIR}
          use_existing_script: true
          script_path: "${PW_PARENT_JOB_DIR}/start-service.sh"
          scheduler: ${{ inputs.cluster.scheduler }}
          slurm:
            is_disabled: ${{ inputs.cluster.slurm.is_disabled }}
            partition: ${{ inputs.cluster.slurm.partition }}
            scheduler_directives: ${{ inputs.cluster.slurm.scheduler_directives }}
            time: ${{ inputs.cluster.slurm.time }}
          pbs:
            is_disabled: ${{ inputs.cluster.pbs.is_disabled }}
            scheduler_directives: ${{ inputs.cluster.pbs.scheduler_directives }}
      - name: Notify job ended
        early-cancel: any-job-failed
        run: |
          set -x
          pwd
          touch job.ended
          ls -lat job.ended


  wait_for_job_start:
    needs:
      - preprocessing
    ssh:
      remoteHost: ${{ inputs.cluster.resource.ip }}
    steps:
      - name: Wait for job to start
        early-cancel: any-job-failed
        run: |
          set -x
          while [ ! -f job.started ]; do
            if [ -f job.ended ]; then
              echo "(date) Job ended before it started. Exiting."
              exit 1
            fi
            echo "$(date) Waiting for job to start..."
            sleep 5
          done
      - name: Get Hostname
        early-cancel: any-job-failed
        run: |
          set -x
          HOSTNAME=$(cat HOSTNAME)
          echo "HOSTNAME=${HOSTNAME}" | tee -a $OUTPUTS

          if [ -z "${HOSTNAME}" ]; then
            echo "$(date) Failed to get target hostname"
            exit 1
          fi

  cleanup:
    if: ${{ always }}
    needs:
      - session_runner
      - wait_for_job_start
    ssh:
      remoteHost: ${{ inputs.cluster.resource.ip }}
    steps:
      - name: Controller cleanup
        if: ${{ inputs.cluster.slurm.is_disabled && inputs.cluster.pbs.is_disabled }}
        run: echo "(date) Cleaning up..."
        cleanup: |
          set -x
          if [ -f cancel.sh ]; then
            bash cancel.sh
          fi
      - name: Compute cleanup
        if: ${{ inputs.cluster.slurm.is_disabled == false || inputs.cluster.pbs.is_disabled == false }}
        run: echo "Cleaning up..."
        cleanup: |
          set -x
          remote_host="${{ needs.wait_for_job_start.outputs.HOSTNAME }}"
          if [ -z "${remote_host}" ]; then
            echo "(date) WARNING: Compute node's hostname is missing. Exiting step."
            exit 0
          fi
          sshcmd="ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${remote_host}"
          if [ -f cancel.sh ]; then
            ${sshcmd} 'bash -s' < ${PWD}/cancel.sh
          fi

  create_session:
    needs:
      - wait_for_job_start
    ssh:
      remoteHost: ${{ inputs.cluster.resource.ip }}
    steps:
      - name: Get Session Port
        early-cancel: any-job-failed
        run: |
          set -x
          SESSION_PORT=$(cat SESSION_PORT)
          echo "SESSION_PORT=${SESSION_PORT}" | tee -a $OUTPUTS

          if [ -z "${SESSION_PORT}" ]; then
            echo "$(date) Failed to get target session's port"
            exit 1
          fi
      - name: Wait for Server To Start
        early-cancel: any-job-failed
        run: |
          TIMEOUT=5
          RETRY_INTERVAL=3
          remote_host="${{ needs.wait_for_job_start.outputs.HOSTNAME }}"
          remote_port="${{ needs.create_session.outputs.SESSION_PORT }}"

          # Function to check if server is listening
          check_server() {
              curl --silent --connect-timeout "$TIMEOUT" "http://${remote_host}:${remote_port}" >/dev/null 2>&1
              return $?
          }

          # Main loop
          attempt=1
          while true; do
              echo "$(date) Attempt $attempt: Checking if server is listening on ${remote_host}:${remote_port}..."
              
              if check_server; then
                  echo "$(date) Success: Server is listening on ${remote_host}:${remote_port}!"
                  exit 0
              elif [ -f job.ended ]; then
                  echo "$(date) Job was completed. Exiting... "
                  exit 0
              else
                  echo "$(date) Server not responding. Retrying in ${RETRY_INTERVAL} seconds..."
                  sleep "$RETRY_INTERVAL"
                  ((attempt++))
              fi
          done
      - name: Expand Slug
        early-cancel: any-job-failed
        run: |
          echo "slug=?folder=${{ inputs.service.directory }}" | tee -a $OUTPUTS
      - name: Update Session
        uses: parallelworks/update-session
        with:
          target: '${{ inputs.cluster.resource.id }}'
          name: '${{ sessions.session }}'
          slug: '${{ needs.create_session.outputs.slug }}'
          remoteHost: '${{ needs.wait_for_job_start.outputs.HOSTNAME }}'
          remotePort: '${{ needs.create_session.outputs.SESSION_PORT }}'

'on':
  execute:
    inputs:
      cluster:
        type: group
        label: Compute Cluster Settings
        items:
          resource:
            type: compute-clusters
            label: Service host
            include-workspace: false
            tooltip: Resource to host the service
          scheduler:
            type: boolean
            default: false
            label: Schedule Job?
            hidden: ${{ inputs.cluster.resource.schedulerType == '' }}
            ignore: ${{ .hidden }}
            tooltip: |
              Yes → Job is submitted to the scheduler using sbatch, qsub, etc
              No  → Job is executed in the controller or login node instead
          slurm:
            type: group
            label: SLURM Directives
            hidden: ${{ inputs.cluster.resource.provider == 'existing' && inputs.cluster.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false  }}
            items:
              is_disabled:
                type: boolean
                hidden: true
                default: ${{ inputs.cluster.resource.provider == 'existing' && inputs.cluster.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false  }}
                label: Is SLURM disabled?
              partition:
                type: slurm-partitions
                label: SLURM partition
                ignore: ${{ inputs.cluster.resource.provider == 'existing' && inputs.cluster.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
                optional: true
                resource: ${{ inputs.cluster.resource }}
                tooltip: Select a partition from the drop down menu.
              time:
                label: Walltime
                type: string
                default: '01:00:00'
                ignore: ${{ inputs.cluster.resource.provider == 'existing' && inputs.cluster.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false  }}
                tooltip: '--time= SLURM directive to set the maximum wall-clock time limit for the job'
              scheduler_directives:
                type: editor
                ignore: ${{ inputs.cluster.resource.provider == 'existing' && inputs.cluster.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false  }}
                optional: true
                tooltip: |
                  Type in additional scheduler directives. 
          pbs:
            type: group
            label: PBS Directives
            hidden: ${{ inputs.cluster.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
            items:
              is_disabled:
                type: boolean
                hidden: true
                default: ${{ inputs.cluster.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false  }}
                label: Is PBS disabled?
              scheduler_directives:
                label: Scheduler Directives
                type: editor
                tooltip: Type the PBS scheduler directives
                hidden: ${{ inputs.cluster.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false  }}

      service:
        type: group
        label: VS Code Settings
        collapsed: true
        items:
          name:
            type: string
            hidden: true
            default: openvscode
          download_url:
            label: Download URL
            type: string
            default: https://github.com/coder/code-server/releases/download/v4.105.1/code-server-4.105.1-linux-amd64.tar.gz
            tooltip: Downloads or uses the code-server server version specified in the URL
          password:
            label: Password for IDE session
            type: password
            optional: true
            tooltip: Enter password or leave blank for no password
          directory:
            label: Directory to open in VS Code
            type: string
            default: ${HOME}
            tooltip: Directory to open in VS code

      juice:
        type: group
        label: Attached GPU Settings
        collapsed: true
        hidden: ${{ org.JUICE_TOKEN == "" }}
        items:
          use_juice:
            label: Enable Juice?
            type: boolean
            default: false
            tooltip: Enable Juice to access and share remote GPUs over a network for your workload.
          pool_ids:
            label: Pool IDs
            type: string
            hidden: ${{ inputs.juice.use_juice == false }}
            ignore: ${{ .hidden }}
            optional: true
            tooltip: Comma separated list of pool ids from which to allocate the session resources, when empty any available pool you have access to is used
          vram:
            label: VRAM
            type: string
            hidden: ${{ inputs.juice.use_juice == false }}
            ignore: ${{ .hidden }}
            optional: true
            tooltip: Amount of VRAM requested in gibibytes. Can return a session with fewer bytes if there is not enough space on the device. Suffixes can be provided for convenience. E.g. 4 GiB (default "0")
          cmd_args:
            label: Juice Run Command Arguments
            type: string
            hidden: ${{ inputs.juice.use_juice == false }}
            ignore: ${{ .hidden }}
            optional: true
            tooltip: Optional arguments for the juice run command to customize workload execution, e.g., "--gpu-ids string".
