permissions:
  - '*'
sessions:
  session:
    useTLS: false
    redirect: true

jobs:
  preprocessing:
      ssh:
        remoteHost: ${{ inputs.resource.ip }}
      steps:
        - name: Checkout
          uses: parallelworks/checkout
          with:
            repo: https://github.com/parallelworks/interactive_session.git
            branch: main
            sparse_checkout:
              - ${{ inputs.service.name }}
        - name: Create Inputs
          run: |
            set -x
            # Write PW variables
            env | grep '^PW_' | grep -v 'PW_API_KEY' > inputs.sh
            # Encase values between quotes
            sed -i 's/=\(.*\)/="\1"/' inputs.sh
            # Write input form variables and ensure the pw agent is in the PATH
            cat <<'EOF' >> inputs.sh
            PATH=$HOME/pw:$PATH
            service_parent_install_dir="${{ inputs.service.parent_install_dir }}"
            service_download_url="${{ inputs.service.download_url }}"
            service_password="${{ inputs.service.password }}"
            service_directory="${{ inputs.service.directory }}"
            juice_use_juice="${{ inputs.juice.use_juice }}"
            juice_pool_ids="${{ inputs.juice.pool_ids }}"
            juice_vram="${{ inputs.juice.vram }}"
            juice_cmd_args="${{ inputs.juice.cmd_args }}"
            JUICE_TOKEN="${{ org.JUICE_TOKEN }}"
            EOF
            if ! [ -z "${{ org.JUICE_TOKEN }}" ]; then
              echo "JUICE_TOKEN=${{ org.JUICE_TOKEN }}" >> inputs.sh
            fi
            # Remove empty variables
            sed -i '/=\s*$\|=undefined\s*$/d' inputs.sh
            sed -i '/=""/d' inputs.sh # remove var=""
            # Add export= to all lines
            sed -i 's/^/export /' inputs.sh
            # Create slug
            echo "slug=?folder=${{ inputs.service.directory }}" | tee -a $OUTPUTS

  session_runner:
    needs:
      - preprocessing
    ssh:
        remoteHost: ${{ inputs.resource.ip }}
    steps:
      - uses: marketplace/session_runner/v1.3
        early-cancel: any-job-failed
        with:
          session: ${{ sessions.session }}
          resource: ${{ inputs.resource }}
          cluster:
            scheduler: ${{ inputs.cluster.scheduler }}
            slurm:
              is_disabled: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false  }}
              account: ${{ inputs.cluster.slurm.account }}
              partition: ${{ inputs.cluster.slurm.partition }}
              qos: ${{ inputs.cluster.slurm.qos }}
              ntasks: ${{ inputs.cluster.slurm.ntasks }}
              nodes: ${{ inputs.cluster.slurm.nodes }}
              scheduler_directives: ${{ inputs.cluster.slurm.scheduler_directives }}
              time: ${{ inputs.cluster.slurm.time }}
            pbs:
              is_disabled: ${{ inputs.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
              scheduler_directives: ${{ inputs.cluster.pbs.scheduler_directives }}
          service:
            start_service_script: ${PW_PARENT_JOB_DIR}/${{ inputs.service.name }}/start-template-v3.sh
            controller_script: ${PW_PARENT_JOB_DIR}/${{ inputs.service.name }}/controller-v3.sh
            inputs_sh: ${PW_PARENT_JOB_DIR}/inputs.sh
            slug: ${{ needs.preprocessing.outputs.slug }}
            rundir: ${PW_PARENT_JOB_DIR}

'on':
  execute:
    inputs:
      resource:
        type: compute-clusters
        label: Service host
        include-workspace: false
        tooltip: Resource to host the service
      cluster:
        hidden: ${{ inputs.resource.schedulerType == '' }}
        ignore: ${{ inputs.resource.schedulerType == '' }}
        type: group
        label: Compute Cluster Settings
        items:
          scheduler:
            type: boolean
            default: false
            label: Schedule Job?
            tooltip: |
              Yes → Job is submitted to the scheduler using sbatch, qsub, etc
              No  → Job is executed in the controller or login node instead
          slurm:
            type: group
            label: SLURM Directives
            hidden: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
            ignore: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
            items:
              is_disabled:
                type: boolean
                hidden: true
                default: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
                label: Is SLURM disabled?
              account:
                label: SLURM account
                type: slurm-accounts
                resource: ${{ inputs.resource }}
                tooltip: '--account=value slurm directive'
                ignore: ${{ 'existing' != inputs.resource.provider }}
                hidden: ${{ .ignore }}
              partition:
                type: slurm-partitions
                label: SLURM partition
                optional: true
                resource: ${{ inputs.resource }}
                tooltip: '--partition=value SLURM directive'
              qos:
                label: Quality of Service [QoS]
                type: slurm-qos
                resource: ${{ inputs.resource }}
                tooltip: '--qos=value slurm directive'
                ignore: ${{ 'existing' != inputs.resource.provider }}
                hidden: ${{ .ignore }}
              ntasks:
                label: Number of tasks
                type: number
                default: 1
                tooltip: '--ntasks=value slurm directive'
                ignore: ${{ 'existing' != inputs.resource.provider }}
                hidden: ${{ .ignore }}
              nodes:
                label: Number of nodes
                type: number
                default: 1
                tooltip: '--nodes=value slurm directive'
                ignore: ${{ 'existing' != inputs.resource.provider }}
                hidden: ${{ .ignore }}
              time:
                label: Walltime
                type: string
                default: '01:00:00'
                tooltip: '--time= SLURM directive to set the maximum wall-clock time limit for the job'
              scheduler_directives:
                type: editor
                optional: true
                tooltip: |
                  Type in additional scheduler directives. 
          pbs:
            type: group
            label: PBS Directives
            hidden: ${{ inputs.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
            ignore: ${{ inputs.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
            items:
              is_disabled:
                type: boolean
                hidden: true
                default: ${{ inputs.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
                label: Is PBS disabled?
              scheduler_directives:
                label: Scheduler Directives
                type: editor
                tooltip: Type the PBS scheduler directives

      service:
        type: group
        label: VS Code Settings
        collapsed: true
        items:
          name:
            type: string
            hidden: true
            default: openvscode
          parent_install_dir:
            label: Parent Install Directory
            type: string
            default: ${HOME}/pw/software
            tooltip: Defaults to ~/pw/software. Make sure there is enough disk space available!
          download_url:
            label: Download URL
            type: string
            default: https://github.com/coder/code-server/releases/download/v4.105.1/code-server-4.105.1-linux-amd64.tar.gz
            tooltip: Downloads or uses the code-server server version specified in the URL
          password:
            label: Password for IDE session
            type: password
            optional: true
            tooltip: Enter password or leave blank for no password
          directory:
            label: Directory to open in VS Code
            type: string
            default: ${HOME}
            tooltip: Directory to open in VS code
