
jobs:
  session_runner:
    if: ${{ inputs.resource.type != 'kubernetes' }}
    needs:
      - preprocessing
    ssh:
        remoteHost: ${{ inputs.resource.ip }}
    steps:
      - name: echo slurm is_disabled
        run: echo ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
      - uses: marketplace/script_submitter/v3.5
        early-cancel: any-job-failed
        with:
          resource: ${{ inputs.resource }}
          shebang: '#!/bin/bash'
          rundir: ${PW_PARENT_JOB_DIR}
          use_existing_script: true
          script_path: "${PW_PARENT_JOB_DIR}/start-service.sh"
          scheduler: ${{ inputs.cluster.scheduler }}
          slurm:
            is_disabled: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
            partition: ${{ inputs.cluster.slurm.partition }}
            scheduler_directives: ${{ inputs.cluster.slurm.scheduler_directives }}
            time: ${{ inputs.cluster.slurm.time }}
          pbs:
            is_disabled: ${{ inputs.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
            scheduler_directives: ${{ inputs.cluster.pbs.scheduler_directives }}


'on':
  execute:
    inputs:
      resource:
        type: compute-resources
        label: Service host
        include-workspace: false
        tooltip: Resource to host the service
      cluster:
        hidden: ${{ inputs.resource.type == 'kubernetes' || inputs.resource.schedulerType == '' }}
        ignore: ${{ inputs.resource.type == 'kubernetes' || inputs.resource.schedulerType == ''  }}
        type: group
        label: Compute Cluster Settings
        items:
          scheduler:
            type: boolean
            default: false
            label: Schedule Job?
            tooltip: |
              Yes → Job is submitted to the scheduler using sbatch, qsub, etc
              No  → Job is executed in the controller or login node instead
          slurm:
            type: group
            label: SLURM Directives
            hidden: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
            ignore: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
            items:
              is_disabled:
                type: boolean
                hidden: true
                default: ${{ inputs.resource.provider == 'existing' && inputs.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
                label: Is SLURM disabled?
              partition:
                type: slurm-partitions
                label: SLURM partition
                optional: true
                resource: ${{ inputs.resource }}
                tooltip: Select a partition from the drop down menu.
              time:
                label: Walltime
                type: string
                default: '01:00:00'
                tooltip: '--time= SLURM directive to set the maximum wall-clock time limit for the job'
              scheduler_directives:
                type: editor
                optional: true
                tooltip: |
                  Type in additional scheduler directives. 

     