app:
jobs:
  job1:
    steps:
      - name: echo on remote host
        run: echo ${{ inputs.hello }}
'on':
  execute:
    inputs:
      hello:
        type: string
        label: Hello message
        