jobs:
  main:
    steps:
      - name: Preprocessing
        run: ./utils/steps/preprocessing.sh
      - name: Validating Target Resource
        run: ./utils/steps/input_form_resource_wrapper.sh
      - name: Process Inputs
        run: ./utils/steps/process_inputs_sh.sh
      - name: Controller Preprocessing
        run: ./utils/steps/controller_preprocessing.sh
      - name: Prepare Service JSON
        run: ./utils/steps/prepare_service_json.sh
      - name: Initialize Cancel Script
        run: ./utils/steps/initialize_cancel_script.sh
      - name: Create Session Script
        run: ./utils/steps/create_session_script.sh
      - name: Launch Job and Wait
        run: ./utils/steps/launch_job_and_wait.sh
        cleanup: ./kill.sh
      - name: Clean and Exit
        run: ./utils/steps/clean_and_exit.sh

'on':
  execute:
    inputs:
      pwrl_host:
        type: group
        label: Service Host
        items:
          resource:
            type: compute-clusters
            label: Service host
            include-workspace: false
            tooltip: Resource to host the service
          nports:
            type: number
            label: Number of Ports to Reserve
            hidden: true
            default: 1
          jobschedulertype:
            type: dropdown
            label: Select Controller or SLURM Partition
            default: CONTROLLER
            options:
              - value: CONTROLLER
                label: Controller
              - value: SLURM
                label: SLURM Partition
            tooltip: Job will be submitted using SSH or sbatch, respectively
          _sch__dd_account_e__tag_existing:
            label: SLURM account
            type: slurm-accounts
            resource: ${{ inputs.pwrl_host.resource }}
            tooltip: Account to submit the interactive job
            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype  || 'existing' != inputs.pwrl_host.resource.provider }}
            ignore: ${{ .hidden }}
            optional: ${{ .hidden }}
          _sch__dd_partition_e__tag_existing:
            type: dropdown
            label: SLURM partition
            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype  || 'existing' != inputs.pwrl_host.resource.provider }}
            ignore: ${{ .hidden }}
            options:
              - label: service
                value: service
            default: service
            tooltip: >-
              Partition to submit the interactive job. Leave empty to let SLURM
              pick the optimal option.
          qos_tag_existing:
            label: Quality of Service [QoS]
            type: slurm-qos
            resource: ${{ inputs.pwrl_host.resource }}
            tooltip: Select a QOS from the drop down menu
            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype  || 'existing' != inputs.pwrl_host.resource.provider }}
            ignore: ${{ .hidden }}
            optional: ${{ .hidden }}
          _sch__dd_ntasks_e__tag_existing:
            label: Number of tasks
            type: number
            min: 1
            max: 100
            default: 1
            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype  || 'existing' != inputs.pwrl_host.resource.provider }}
            ignore: ${{ .hidden }}
          _sch__dd_nodes_e__tag_existing:
            label: Number of nodes
            type: number
            default: 1
            hidden: true
            ignore: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype  || 'existing' != inputs.pwrl_host.resource.provider }}
          _sch__dd_partition_e__tag_cloud:
            type: slurm-partitions
            label: SLURM partition
            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype  || 'existing' == inputs.pwrl_host.resource.provider }}
            ignore: ${{ .hidden }}
            optional: true
            tooltip: >-
              Partition to submit the interactive job. Leave empty to let SLURM
              pick the optimal option.
            resource: ${{ inputs.pwrl_host.resource }}
          _sch__dd_time_e_:
            label: Walltime
            type: string
            default: 01:00:00
            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype  }}
            ignore: ${{ .hidden }}
            tooltip: e.g. 01:00:00 - Amount of time slurm will honor the interactive session.
          scheduler_directives_slurm:
            type: string
            label: Scheduler directives
            hidden: ${{ 'SLURM' != inputs.pwrl_host.jobschedulertype }}
            ignore: ${{ .hidden }}
            optional: true
            tooltip: >-
              e.g. --mem=1000;--gpus-per-node=1 - Use the semicolon character ;
              to separate parameters. Do not include the SBATCH keyword.
        collapsed: false
      service:
        type: group
        label: Service
        items:
          novnc_parent_install_dir:
            label: noVNC installation directory
            type: string
            hidden: true
            default: __HOME__/pw/software
          novnc_tgz_basename:
            label: Basename of the novnc tgz file
            type: string
            hidden: true
            default: noVNC-1.5.0.tgz
          name:
            type: dropdown
            label: Select remote display protocol
            options:
              - label: VNC Server
                value: turbovnc
              - label: Nice DCV
                value: nicedcv
              - label: Scyld Cloud Workstation
                value: scw
            tooltip: Make sure the display protocol is installed in the host!
            default: turbovnc
            hidden: ${{ 'existing' == inputs.pwrl_host.resource.provider }}
          vnc_type:
            label: VNC Server Type
            type: string
            default: turbovnc
            hidden: true
            ignore: ${{ 'existing' != inputs.pwrl_host.resource.provider }}
          desktop:
            label: Desktop Session
            type: string
            default: mate-session
            hidden: true
            ignore: ${{ 'existing' != inputs.pwrl_host.resource.provider }}
          load_env:
            label: Command to load ARM Forge to the PATH
            type: string
            default: module load forge
            tooltip: 'To load the environment, enter the appropriate command, for example: module load module-name or source path/to/env.sh.'
          bin:
            label: Command to launch ARM Forge
            type: string
            default: forge
            tooltip: Command to start ARM Forge
          background:
            label: Run service in background
            type: boolean
            default: true
            hidden: true
