# yaml-language-server: $schema=https://activate.parallel.works/workflow.schema.json
permissions:
  - '*'

jobs:
  preprocessing:
      ssh:
        remoteHost: ${{ inputs.cluster.resource.ip }}
      steps:
        - name: Checkout
          uses: parallelworks/checkout
          with:
            repo: https://github.com/parallelworks/interactive_session.git
            branch: main
            sparse_checkout:
              - ${{ inputs.service.name }}
        - name: Create Inputs
          run: |
            set -x
            # Write PW variables
            env | grep '^PW_' | grep -v 'PW_API_KEY' > inputs.sh
            # Encase values between quotes
            sed -i 's/=\(.*\)/="\1"/' inputs.sh
            # Write input form variables and ensure the pw agent is in the PATH
            cat <<'EOF' >> inputs.sh
            PATH=$HOME/pw:$PATH
            service_parent_install_dir="${{ inputs.service.novnc_parent_install_dir }}"
            service_novnc_tgz_basename="${{ inputs.service.novnc_tgz_basename }}"
            pw_endpoints_args="--name ${{ inputs.service.name }}-${PW_RUN_SLUG}"
            EOF
            # Remove empty variables
            sed -i '/=\s*$\|=undefined\s*$/d' inputs.sh
            sed -i '/=""/d' inputs.sh # remove var=""
            # Add export= to all lines
            sed -i 's/^/export /' inputs.sh
        - name: Controller Preprocessing
          run: |
            set -x
            # This script prepares the target host and always runs in the controller node
            cp inputs.sh controller-${PW_JOB_ID}.sh
            cat ${{ inputs.service.name }}/controller-v4.sh >> controller-${PW_JOB_ID}.sh
            bash controller-${PW_JOB_ID}.sh
        - name: Create Service Script
          run: |
            rm -f HOSTNAME SESSION_PORT job.ended job.started
            # This script starts the service
            cp inputs.sh start-service-${PW_JOB_ID}.sh

            # Write code common to all services
            cat <<'EOF' >> start-service-${PW_JOB_ID}.sh

            cleanup() {
                trap - EXIT INT TERM HUP QUIT USR1 USR2 PIPE
                echo "::notice::Cleaning up..."
                if [ -f cancel.sh ]; then
                    mv cancel.sh cancel.sh.submitted
                    echo "echo Cleanup script was already executed" > cancel.sh
                    bash cancel.sh.submitted
                fi
                kill -- -$$
            }

            trap cleanup EXIT INT TERM HUP QUIT USR1 USR2 PIPE

            echo "::notice::Starting service"
            EOF
            cat ${{ inputs.service.name }}/start-template-v4.sh >> ./start-service-${PW_JOB_ID}.sh
            echo "SCRIPT_PATH=${PWD}/start-service-${PW_JOB_ID}.sh" | tee -a $OUTPUTS
            echo "SKIP_CLEANUP_PATH=${PWD}/SKIP_CLEANUP" | tee -a $OUTPUTS

  session_runner:
    needs:
      - preprocessing
    ssh:
      remoteHost: ${{ inputs.cluster.resource.ip }}
    steps:
      - name: Session Runner
        uses: github/parallelworks/interactive_session@main
        early-cancel: any-job-failed
        with:
          $yaml: workflow/script_submitter/v3.6/general.yaml
          resource: ${{ inputs.cluster.resource }}
          shebang: '#!/bin/bash'
          use_existing_script: true
          script_path: ${{ needs.preprocessing.outputs.SCRIPT_PATH }}
          define_cleanup_script: true
          cleanup_script_path: ./cancel.sh
          scheduler: ${{ inputs.cluster.scheduler }}
          use_scheduler_agent: false
          submit_and_exit: false
          skip_cleanups_file: ${{ needs.preprocessing.outputs.SKIP_CLEANUP_PATH }}
          slurm:
            is_enabled: ${{ inputs.cluster.slurm.is_enabled }}
            partition: ${{ inputs.cluster.slurm.partition }}
            scheduler_directives: ${{ inputs.cluster.slurm.scheduler_directives }}
            time: ${{ inputs.cluster.slurm.time }}
          pbs:
            is_enabled: ${{ inputs.cluster.pbs.is_enabled }}
            scheduler_directives: ${{ inputs.cluster.pbs.scheduler_directives }}


  wait_for_endpoint:
    needs:
      - preprocessing
    ssh:
      remoteHost: ${{ inputs.cluster.resource.ip }}
    steps:
      - name: Wait for endpoint
        early-cancel: any-job-failed
        run: |
          endpoint_name="${{ inputs.service.name }}-${PW_RUN_SLUG}"
          echo "::notice::Waiting for endpoint ${endpoint_name} to come online"
          until pw endpoints list | grep -qw "${endpoint_name}"; do
            echo "$(date) Endpoint ${endpoint_name} not found yet; retrying in 10 seconds"
            sleep 10
          done
          echo "::notice::Endpoint ${endpoint_name} is online"
          touch ${{ needs.preprocessing.outputs.SKIP_CLEANUP_PATH }}
          sleep 2
      - name: Cancel Script Submitter
        uses: parallelworks/cancel-jobs
        with:
          jobs:
            - session_runner


'on':
  execute:
    inputs:
      cluster:
        type: group
        label: Compute Cluster Settings
        items:
          resource:
            type: compute-clusters
            label: Service host
            include-workspace: false
            tooltip: Resource to host the service
          scheduler:
            type: boolean
            default: false
            label: Schedule Job?
            hidden: ${{ inputs.cluster.resource.schedulerType == '' }}
            ignore: ${{ .hidden }}
            tooltip: |
              Yes → Job is submitted to the scheduler using sbatch, qsub, etc
              No  → Job is executed in the controller or login node instead
          slurm:
            type: group
            label: SLURM Directives
            hidden: ${{ inputs.cluster.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
            ignore: ${{ inputs.cluster.resource.schedulerType != 'slurm' || inputs.cluster.scheduler == false }}
            items:
              is_enabled:
                type: boolean
                hidden: true
                default: true
                label: Is SLURM enabled? Yes, unless the slurm section is hidden and ignored
              partition:
                type: slurm-partitions
                label: SLURM partition
                optional: true
                resource: ${{ inputs.cluster.resource }}
                tooltip: Select a partition from the drop down menu.
              time:
                label: Walltime
                type: string
                default: '01:00:00'
                tooltip: '--time= SLURM directive to set the maximum wall-clock time limit for the job'
              scheduler_directives:
                type: editor
                optional: true
                tooltip: |
                  Add extra SLURM directives, one per line, using the #SBATCH prefix. For example:
                  #SBATCH --exclusive
                  #SBATCH --nodelist=<node-name>
          pbs:
            type: group
            label: PBS Directives
            hidden: ${{ inputs.cluster.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
            ignore: ${{ inputs.cluster.resource.schedulerType != 'pbs' || inputs.cluster.scheduler == false }}
            items:
              is_enabled:
                type: boolean
                hidden: true
                default: true
                label: Is PBS enabled? Yes, unless the pbs section is hidden and ignored
              scheduler_directives:
                label: Scheduler Directives
                type: editor
                tooltip: |
                  Add extra PBS directives, one per line, using the #PBS prefix. For example:
                  #PBS -l mem=16gb
                  #PBS -l ngpus=1
      service:
        type: group
        hidden: true
        label: Webshell
        items:
          name:
            type: string
            hidden: true
            default: webshell
          novnc_parent_install_dir:
            label: noVNC installation directory
            type: string
            hidden: true
            default: ${HOME}/pw/software
          novnc_tgz_basename:
            label: Basename of the novnc tgz file
            type: string
            hidden: true
            default: noVNC-1.3.0.tgz
